

export default function CandleParams(){
    const canndleNames = [
  "lush gardenia",
  "tropical dragonfruit",
  "pink sands™ glow",
  "twilight nectar",
  "kitchen spice™",
  "rustling rain",
  "a fresh chapter",
  "enchanted orchard",
  "silver sage & pine",
  "lemon gelato",
  "vintage velvet",
  "canyon pine",
  "lemon lavender",
  "snow globe wonderland",
  "petal",
  "glistening leaves",
  "cucumber mint cooler",
  "cinnamon stick",
  "christmas eve®",
  "christmas cookie™",
  "midnight jasmine",
  "pink sands™",
  "café al fresco",
  "magical bright lights",
  "whimsical water lily",
  "white spruce & grapefruit",
  "paradise pumpkin",
  "beach walk®",
  "banana cream",
  "strawberry swirl",
  "lemon blueberry bliss",
  "blooming love",
  "juicy watermelon",
  "honey clementine",
  "coastal cliffhanger",
  "a calm & quiet place",
  "boo-nana toffee",
  "moonlit woods",
  "mediterranean breeze",
  "amethyst air",
  "olive & cypress",
  "velvet joy",
  "vanilla cupcake",
  "lilac blossoms",
  "yuletide wishes",
  "holiday sage®",
  "twinkling tinsel",
  "apple pumpkin",
  "harvest gems",
  "seaside woods",
  "merry mingle",
  "balsam & cedar santa",
  "golden honey",
  "pink pumpkin",
  "ocean air",
  "black cherry",
  "dolce",
  "sugared cinnamon apple",
  "strawberry bunny shortcake decorative tumbler candle",
  "catching rays™",
  "heritage oak",
  "marshmallow forest",
  "jelly beans",
  "french vanilla",
  "caramel kiss",
  "lavender vanilla",
  "harvest®",
  "marine",
  "tangerine & vanilla",
  "happy home",
  "fresh powder",
  "balsam & cedar fireside",
  "sparkling pinkberry",
  "cliffside sunrise",
  "nectar",
  "salted coconut",
  "starfruit & sunshine",
  "lavender bliss",
  "sparkling snow™",
  "midsummer's night®",
  "fruit splash",
  "dried lavender & oak",
  "chocolate layer cake",
  "driftwood rose",
  "sun club - lemon & white rose",
  "clean cotton®",
  "amber & sandalwood",
  "soft cashmere",
  "santa's cookies",
  "big apple christmas",
  "denim dreams",
  "golden pumpkin",
  "toasted old fashioned",
  "white strawberry bellini",
  "macintosh",
  "coconut beach",
  "honeysuckle grove",
  "vanilla flurries",
  "enchanting cherry blossoms",
  "frosty glow",
  "sun & sand®",
  "beach escape",
  "home sweet home®",
  "sugared neroli",
  "green apple sorbet",
  "snow-capped sledding",
  "bahama breeze™",
  "mountain lodge™",
  "chérie lollipop",
  "iced berry lemonade",
  "slow bloom",
  "autumn leaves®",
  "balsam & cedar",
  "amber",
  "social birdie - melon & spun sugar",
  "garden showers",
  "north pole frost",
  "spiced pumpkin",
  "black coconut",
  "lilies & lace",
  "crisp fall night",
  "fresh cut roses",
  "serenity stone",
  "strawberry bunny shortcake",
  "floral drift",
  "christmas magic",
  "conductor's coal",
  "lucky shamrock™",
  "dried lavender & oak​",
  "vanilla lime",
  "amber bouquet",
  "sweet moments",
  "vanilla crème brûlée",
  "warm luxe cashmere",
  "hoppy easter",
  "bayside cedar",
  "santa on skis",
  "peaches & peonies",
  "holiday winterfest",
  "winter pine",
  "cocoa dream",
  "liberty bloom",
  "sparkling cinnamon",
  "shimmering christmas tree",
  "tree farm festival",
  "chérie lollipop heart candle",
  "pumpkin banana scone",
  "autumn wreath™",
  "’tis the sea-sun in sydney",
  "star-spangled blueberry",
  "sakura blossom festival",
  "apothecary potions",
  "sicilian lemon",
  "train car carols",
  "on the green - pear & water lily",
  "easter bouquet",
  "citron",
  "wildflower breeze",
  "amber linen",
  "spring herbarium",
  "wild orchid",
  "frosted tracks",
  "sage & citrus",
  "summit stargazing"
]
    const candleStyles = [
  "small tumbler",
  "three wick",
  "two-wick",
  "large tumbler",
  "medium pillar",
  "not listed",
  "mini",
  "jar"
]
    const candleFragrances = [
  "solar bloom",
  "ripe strawberry",
  "aromatic juniper",
  "dune grass",
  "coconut cream",
  "peach",
  "red fruits",
  "sweet bourbon",
  "coconut",
  "coffee milk",
  "midnight jasmine",
  "myrtle",
  "wild moss",
  "sweet caramel",
  "tart lemon",
  "peppercorn",
  "juicy pink apple",
  "blood orange",
  "velvet amber",
  "oakmoss",
  "creamed butter",
  "coconut milk",
  "rum barrel",
  "warm wool",
  "caramelized sugar",
  "malted sugar",
  "marshmallow",
  "golden pineapple",
  "fresh air",
  "beach musk",
  "pear nectar",
  "tahitian vanilla",
  "sugar​",
  "balsam",
  "peony",
  "pinecones",
  "white cedar",
  "fir needle",
  "fruity apple peel",
  "pear blossom",
  "verbena blossom",
  "monoi blooms",
  "juniper berry",
  "juicy pear",
  "fresh cypress",
  "baked vanilla",
  "cranberry",
  "white flowers",
  "cassis",
  "cinnamon",
  "pine needles",
  "bleached woods",
  "green palm",
  "airy ozone",
  "sweet patchouli",
  "brown sugar",
  "vanilla cookie",
  "watery accents",
  "frothy milk",
  "whipped vanilla malt",
  "orange blossom",
  "fruity cranberry",
  "bright bergamot",
  "frangipani",
  "lavandin",
  "mineral air",
  "fluffy marshmallow",
  "sunscreen",
  "orange zest",
  "melon",
  "icy citrus",
  "passion fruit",
  "milk accords",
  "almond flower",
  "cedarwood​",
  "caramel",
  "strawberry leaf",
  "green herbal",
  "woody notes",
  "cherry",
  "lei blossom",
  "fresh clover",
  "sappy needles",
  "golden amber praline",
  "whipped cream",
  "apple slices",
  "fluffy white florals",
  "oak",
  "sandy woods",
  "leather",
  "red berry",
  "ambery musk",
  "crystallized sugar",
  "black currant",
  "candied violet",
  "almond milk",
  "glowing tuberose",
  "pine needle",
  "blue musk",
  "pink lemon",
  "evergreen",
  "tea leaves",
  "fresh cut grass",
  "frosted white musk",
  "pineapple",
  "clove",
  "jasmine",
  "wet stone accord",
  "frilly fern",
  "cashew milk",
  "sheer musk",
  "fresh mango",
  "tobacco leaf",
  "mineral waters",
  "whipped vanilla",
  "patchouli",
  "mulberry",
  "driftwood",
  "raspberry",
  "white amber",
  "caramel drizzle",
  "pepper",
  "juicy raspberry",
  "tropical blooms",
  "pink peppercorn",
  "iced amber",
  "coconut pulp",
  "nutmeg",
  "solar florals",
  "fresh eucalyptus",
  "dewy pear",
  "violet",
  "sueded leather",
  "brandy",
  "tomato leaf",
  "spice",
  "island woods",
  "fluffy cotton candy",
  "geranium leaf",
  "lemon sugar",
  "sweet vanilla",
  "cedarleaf",
  "tiare flower",
  "cinnamon sprinkle",
  "rich balsam",
  "lilac petals",
  "watermelon",
  "midnight patchouli",
  "cinnamon leaf",
  "iced lemon",
  "fresh-squeezed orange",
  "orange",
  "cactus blossom",
  "aromatic lavender",
  "red maple leaf",
  "tangerine",
  "red currant",
  "sea daffodil",
  "velvet petals",
  "cake batter",
  "fresh gariguette strawberries",
  "grapefruit",
  "sun-kissed amber",
  "cedar",
  "juicy grape",
  "lily",
  "fluffy musk",
  "cashmere woods",
  "red thyme",
  "cocoa",
  "pink grapefruit",
  "icy lemon",
  "pie crust",
  "sugarcane",
  "vanilla bean",
  "crisp cotton",
  "hemlock cones",
  "fresh greens",
  "sliced watermelon",
  "soft musk",
  "blue chamomile",
  "coconut water",
  "tropical fruits",
  "cyclamen",
  "watery green ozonic",
  "red hot cinnamon",
  "fresh herbs",
  "pink papaya",
  "toffee",
  "cherry jam",
  "white rose",
  "juicy orange",
  "crisp ozone",
  "pear",
  "coriander",
  "fennel",
  "praline",
  "plum blossom",
  "black peppercorn",
  "woody pine",
  "boxwood pine",
  "creamy sandalwood",
  "mandarin bellini",
  "velvet woods",
  "fresh vanilla",
  "honey",
  "tobacco",
  "juicy macintosh",
  "airy breeze",
  "evergreens",
  "blue surf accord",
  "pinecone",
  "herbaceous",
  "velvet peach",
  "pink pepper",
  "apple blossom",
  "apricot",
  "cream",
  "moss",
  "aromatic",
  "ozonic",
  "crushed clove",
  "kaffir lime",
  "toasted marshmallow",
  "sweet cherry",
  "baked pie crust",
  "praline glaze",
  "sugared musk",
  "tuberose",
  "ozone",
  "pine cones",
  "white lily",
  "meyer lemon",
  "passionfruit",
  "leafy greens",
  "cinnamon spice",
  "iced eucalyptus",
  "charcoal accord",
  "birch",
  "pumpkin spice",
  "maple leaf",
  "mediterranean sage",
  "frozen lemon",
  "sliced apple",
  "cool shade",
  "orange peel",
  "hibiscus",
  "peppermint",
  "vanilla orchid",
  "cotton flower",
  "cream of coconut",
  "sweet strawberry",
  "dewy rose",
  "geranium",
  "apple spice",
  "spring lilac",
  "aloe vera",
  "chantilly cream",
  "sugared pine needles",
  "vanilla",
  "fresh coconut",
  "amber silk",
  "chocolate mousse pudding",
  "mango",
  "musky",
  "banana",
  "sea minerals",
  "orris",
  "harvest peach",
  "moss​",
  "water lily",
  "sugar crystals",
  "dewdrops",
  "magnolia",
  "cottonwood",
  "coumarin",
  "winter iris",
  "white peach",
  "yellow fruits",
  "sloe berries",
  "baked cookie",
  "sparkling wine nectar",
  "osmanthus",
  "blue spruce",
  "sweet grass",
  "white grapefruit",
  "musk",
  "powdery",
  "lilac",
  "gingersnap",
  "marine accord",
  "freshness",
  "anise",
  "balsam needle",
  "star anise",
  "spun sugar",
  "dragonfruit",
  "vetiver",
  "ripe kiwi",
  "fruity musk",
  "gardenia",
  "berry",
  "caramel rum",
  "cashmere musk",
  "honeysuckle",
  "iridescent opal",
  "icy snow",
  "charred woods",
  "powdery accord",
  "blueberry",
  "red berries",
  "citrus",
  "citron",
  "pomegranate",
  "elemi",
  "mint leaf",
  "blue ozone",
  "frosted snow",
  "vanilla sugar",
  "vanilla woods",
  "bitter orange",
  "buttercream",
  "sea moss",
  "lychee",
  "hinoki wood",
  "warm cashmere",
  "honey bee pollen",
  "fresh pineapple",
  "cypress",
  "heavy cream",
  "suede",
  "aloe",
  "vanilla cream",
  "lime",
  "white pine",
  "pine needle sap",
  "salty air",
  "watery marine",
  "red raspberry",
  "sugared berries",
  "condensed milk",
  "pine",
  "cucumber",
  "twinkling lights",
  "violet leaf",
  "pink pomegranate",
  "sparkling bergamot",
  "hints of spice",
  "lemon zest",
  "cool lavender",
  "autumn spice",
  "snow moss",
  "star jasmine",
  "birch leaf",
  "palm leaf",
  "water musk",
  "frozen pear",
  "spicy cardamom",
  "cherry blossom",
  "red rose",
  "eucalyptus",
  "sweet mandarin",
  "airy musk",
  "fir needles",
  "sage",
  "pink kiwi",
  "sunny ozone",
  "ylang ylang",
  "woody",
  "ambrette",
  "fresh cucumber",
  "floral sage",
  "tart berry",
  "saguaro cactus",
  "exotic fruits",
  "bergamot​",
  "solar gardenia",
  "amber sands",
  "sweet honeysuckle",
  "verbena",
  "white honey",
  "watery",
  "rich plum",
  "smoked vanilla",
  "wild lily",
  "clary sage",
  "banana ice sorbet",
  "sandalwood",
  "crisp citrus",
  "fruity notes",
  "green apple",
  "coconut blossom",
  "petitgrain",
  "strawberry nectar",
  "juicy blueberries",
  "sugar",
  "muddled blueberry",
  "wood moss",
  "crisp bergamot",
  "candy apple",
  "creamy vanilla",
  "black raspberry",
  "nectarine",
  "orange blossoms",
  "maple",
  "ceylon cinnamon",
  "bitters",
  "malt",
  "pine sap",
  "caramel swirl",
  "tobacco flower",
  "acacia",
  "iris",
  "butter",
  "citrus zest",
  "lily of the valley",
  "white musk",
  "sugared violet",
  "mandarin leaf",
  "soft powder",
  "cool citrus",
  "white sage",
  "sweet milk",
  "warm amber",
  "warm cinnamon",
  "musky woods",
  "tulip bulbs",
  "lemon",
  "green leaf",
  "wet soil",
  "black tea",
  "bergamot",
  "tonka",
  "chilled sparkling wine",
  "ice cream",
  "barley grass",
  "narcissus",
  "lavender",
  "pumpkin puree",
  "violet leaves",
  "cassis bud",
  "dewy greens",
  "cumin",
  "strawberry",
  "muguet",
  "creamy musk",
  "fresh ginger",
  "hyacinth",
  "orchard nectarine",
  "effervescent citrus",
  "aldehydes",
  "rainbow berries",
  "crisp mint",
  "davana",
  "white lace",
  "crisp greens",
  "snowdrop",
  "avocado",
  "icy mint",
  "rich vanilla cream",
  "blue spirulina",
  "wild orchid",
  "white pine needles",
  "golden amber",
  "dewy violet",
  "sun-kissed orange",
  "apple",
  "dwarf citrus",
  "tropical nectar",
  "dandelion",
  "ice cold lemon",
  "rosemary",
  "spruce",
  "citrus blossoms",
  "herbs",
  "ginger",
  "creamy praline",
  "fruity pineapple",
  "cinnamon bark",
  "olive",
  "cinnamon stick",
  "amber woods",
  "sea salt",
  "sesame seed rice",
  "pine balsam",
  "blue sage",
  "banana cream",
  "crisp apple",
  "caramel cream",
  "sweet alyssum",
  "white peppercorn",
  "amber crystals",
  "black pepper",
  "juicy orange​​",
  "powdery notes",
  "cactus flower",
  "cinnamon cider",
  "guaiac wood",
  "mandarin",
  "chilled sparkling wine ​​",
  "whispering willow",
  "basil",
  "white lilies",
  "winter tuberose",
  "cypress wood",
  "white moss",
  "white cardamom",
  "baked pumpkin",
  "amber wood",
  "cardamom",
  "snowdrop petals",
  "tulips",
  "frosted ginger",
  "coffee",
  "ripe fig",
  "creamy jasmine",
  "clementine",
  "warm spices",
  "clove bud",
  "grape jelly beans",
  "wood smoke",
  "cool milky notes",
  "orange flower",
  "sparkly tangerine",
  "blackberry",
  "sweet musk",
  "white pine bark",
  "sheer cyclamen",
  "sea isle muguet",
  "green",
  "neroli",
  "spiced clove",
  "santal",
  "thyme",
  "rose petals",
  "floralcy of rose",
  "pink amber",
  "spicy vanilla",
  "red fruit",
  "blush rose",
  "wild jasmine",
  "tonka bean",
  "hazelnut",
  "cappuccino",
  "rindy grapefruit",
  "festive spices",
  "elderberry",
  "holly berry",
  "vanilla essence",
  "juniper",
  "linen breeze",
  "tropical musk",
  "mint",
  "vanilla icing",
  "fruit",
  "melted sugarcane",
  "heliotrope",
  "freesia",
  "mandarin blossom",
  "holiday spices",
  "lemon peel",
  "salt water",
  "apple peels",
  "fresh strawberry",
  "crabapple",
  "amber musk",
  "sparkling aldehydes",
  "cedarwood",
  "silver spruce",
  "sparkling citrus",
  "ruby red grapefruit",
  "fir balsam",
  "bay leaf",
  "fresh apple",
  "fresh pine",
  "tart cherry",
  "amber",
  "pecan",
  "dried persimmon tree leaves",
  "yuzu",
  "palm leaves",
  "spiced pumpkin",
  "pomelo",
  "fresh green",
  "incense",
  "cinnamon sugar",
  "mixed blackberries",
  "rose",
  "sweet orange",
  "dried sage",
  "solar tuberose",
  "baked notes",
  "pink apple",
  "creamy vanilla bean",
  "dash of cinnamon",
  "neroli blossom",
  "woody oak",
  "beach amber",
  "earthy greens",
  "golden marshmallow",
  "almond",
  "banana flower",
  "garden rain",
  "chrysanthemum",
  "peach nectar",
  "cashmere",
  "red raspberry jam",
  "african orange flower",
  "saffron",
  "toasted praline",
  "mulled wine accord",
  "water hyacinth",
  "green herbs",
  "sunlit vanilla",
  "honeyed cacao",
  "banana oatmeal pancakes",
  "green pear",
  "sheer woods",
  "pistachio cream",
  "grape",
  "vapour",
  "spearmint",
  "carrot",
  "warm woods",
  "chocolate",
  "smoky embers",
  "orchid petals"
]
    
    return(
        <>
        <div className="flex flex-col items-center justify-center h-screen">
            <div className="flex flex-col items-center justify-center w-[75vw] h-[55vh] border-4 border-gray-300 rounded-2xl md:w-1/2 lg:w-1/3 font-poppins">
                <label htmlFor='candleName'>Candle Name</label>
                <input list="candleName_List" id="candleName" name="candleName" className="border-2 border-black-200"></input>
                <label htmlFor='candleStyle'>Candle Style</label>
                <input list="candleStyle_List" id="candleStyle" name="candleStyle" className="border-2 border-black-200"></input>
                <label htmlFor='candleFragrances'>Candle Fragrances</label>
                <input list="candleFragrances_List" id="candleFragrances" name="candleFragrances" className="border-2 border-black-200"></input>
                <button type='button' className='border-2 w-24 hover:bg-gray-500 transition-colors'>Search</button>
            </div>
        </div>
            

            <datalist id='candleName_List'>
                {canndleNames.map((name) => (
                    <option key={name} value={name} />
                ))}
            </datalist>

            <datalist id='candleStyle_List'>
                {candleStyles.map((style) => (
                    <option key={style} value={style} />
                ))}
            </datalist>

            <datalist id='candleFragrances_List'>
                {candleFragrances.map((fragrance) => (
                    <option key={fragrance} value={fragrance} />
                ))}
            </datalist>
        </>
    )
}